### ISSUE TITLE
1.1 (Official Release) Todo

### ISSUE THREAD

**Issue by Leo40Git** [Leo40Git/CaveSaveEdit#3]
- [x] FIX NPCS!!!!!!
- [x] Clicking and releasing immediately without moving your cursor in the MapView window moves quote, and it also doesn't move him to where you clicked in the MapView. (it's far up/right from where you click)
- [x] ~~Still can't hold two arrows to move directionally in the MapView window.~~
- [x] You still gotta move your cursor at least one pixel before Quote moves to your cursor. This means that you can't just click.
- [x] Scrollbar needs to be moveable by mouse.
- [x] ~~Read weapon and item names from TSC files.~~
- [x] ~~Add CS+ support.~~ *See #6.*
- [x] Complete the flag list.

**Comment by Leo40Git** [comment]
d50df589c04ce1851e4b7b3bfd2e3dd6e5ceb7f9 makes scrollbars moveable using the mouse, so it's getting marked off the list.
**EDIT:** 3d953adb764963a2dc4a9871595393e6ad6340ba marks the completion of mouse-controllable scrollbars!

**Comment by Leo40Git** [comment]
NPCs might be fixed already, though I haven't ported framerects from BL yet to test it.
**EDIT:** NPCs are in fact fixed! Just need to polish up the framerects and add offsets.

**Comment by Leo40Git** [comment]
CS+ support has been delayed to a future release.

**Comment by Leo40Git** [comment]
2f2dc914fe8a7da6cc80d60efd0e2297f1331421 marks the completion of the flaglist! About time.

**Comment by Leo40Git** [comment]
making a new todo list to get the milestone closed
see #7
