### ISSUE TITLE
CS+ Todo

### ISSUE THREAD

**Issue by Leo40Git** [Leo40Git/CaveSaveEdit#6]
- [x] Figure out how to handle multiple profiles
    - [x] Add dialog for manipulating profiles
- [x] Add CS+ specific variables (Special unlocks)
- [x] Add special MCI for CS+ (Grasstown is now Bushlands, different item names, etc)

**Comment by Leo40Git** [comment]
02c5bb0b7ef88845561118e60933eaffd85185f9 adds a special MCI for CS+.

**Comment by Leo40Git** [comment]
ca1034ff72a86acbbd1883f903c2d95bc632812f adds multiple profile handling.

**Comment by Leo40Git** [comment]
A note about Curly Story: it appears files 0-2 are normal profiles, and 3-5 are Curly Story profiles.

**Comment by Leo40Git** [comment]
ef63d68ac66dbd2181ec68a3a4433f69e5424414 adds a dialog for manipulating profiles, and 67127c63740e9888598f82b64e9d7e73d23b99a9 + 0d6f152733f7def435963c4f53fab78b4b5fcf08 add CS+ specific variables (difficulty, last save date, "beaten hell" flag).
This marks the completion of CS+ support!
