### ISSUE TITLE
General Todo

### ISSUE THREAD

**Issue by Leo40Git** [Leo40Git/CaveSaveEdit#7]
- [ ] Still can't hold two arrows to move directionally in the MapView window.
- [ ] Read weapon and item names from TSC files.
- [x] Add Nikumaru/290 Counter (290.rec) editor
  - [x] Check if normal 290.rec and CS+ 290.rec are different (they aren't)

**Comment by Leo40Git** [comment]
c1903863c44df011eaf0cd79e38d32d0b2add6cb adds a 290.rec editor

**Comment by Leo40Git** [comment]
Need to reimplement this for the native-ui branch...
